apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: "https://103.185.52.45:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpFek9UQTRNRFF3SGhjTk1qWXdNakU0TURVd01EQTBXaGNOTXpZd01qRTJNRFV3TURBMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpFek9UQTRNRFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTckpZTUNCdG9kU2lGZ2k1bkJ0YnNRaE4wcTRnSmRJQ2lzeGRwN2FGR00KcTVaWk5iQXpLbjNrd05hU2JmZ2sxL2xUQWFIWnFSUlI0czdqaEFIclhUMjZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXdHdVk4YVZ2QzVURDZnaUdFQlNTCmRrK2loU2t3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnYld1Y1NkQUVsZ3orcmp2Z1hrU0hXTTRSQnlrQVo4VjQKWDBlTjhYZzdJMmNDSVFDZWRtR2pVMzVQaUtheVFnQS9NWHJMd2ZyL1pBeUU3eUJzWHo2bGN5VFZKZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
contexts:
- name: poliwindra
  context:
    cluster: local
    namespace: poliwindra
    user: poliwindra-sa
current-context: poliwindra
users:
- name: poliwindra-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlFteFl2cGk1RkF5TEFkdDJYSC05UnVmUGJhYXJCU0pBNjNEcUZxcEtsdFUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJwb2xpd2luZHJhIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InBvbGl3aW5kcmEtc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoicG9saXdpbmRyYS1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjhlODk1ODg0LWJlYjUtNGMwYi05YzBhLTM4YjJkNWYzY2JkMSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpwb2xpd2luZHJhOnBvbGl3aW5kcmEtc2EifQ.iosWl88AbJRp1SHU0sgFtvsFi_IpiGQzkWnZfFswaTFz5mFZwWtV_BgBWYsxx_UO9lGqtXJET4ug-shSaJJMY9rGk4dPnzqsaCouBVAeRgn7t8IoM6V-Bz3PUWy4P8CMk3wYbqFB0-MBroGaqHJDU0CmleaSks9-dnDkRkEjdKxdahC1Mk9VYCNwHGi-6kszzpNfRnNsNK8arZKgPehDymduQTLo5ZoFZXKM2O3aYSeZWew_SChx-Or15vTw-Hoe1-sfEQeqhWOlLC38Rbf4HCHZKkVFey-41D4m4SoXPkgEkQhoFFwWYxVnaIdAg6X_fSWTeDUhE0OWKDPXAJGhUg
